import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.onPrimaryContainer,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: appTheme.orange900,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 14.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 12.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 24.fSize,
          fontFamily: 'Figtree',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 12.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: 16.fSize,
          fontFamily: 'Figtree',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 14.fSize,
          fontFamily: 'Figtree',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF1E1E1E),
    secondary: Color(0XFF1E1E1E),
    secondaryContainer: Color(0XFF797A7B),
    tertiary: Color(0XFF1E1E1E),
    tertiaryContainer: Color(0XFF797A7B),

    // Background colors
    background: Color(0XFF1E1E1E),

    // Surface colors
    surface: Color(0XFF1E1E1E),
    surfaceTint: Color(0XFF1F2223),
    surfaceVariant: Color(0XFF797A7B),

    // Error colors
    error: Color(0XFF1F2223),
    errorContainer: Color(0XFF349A56),
    onError: Color(0XFFD2D3D3),
    onErrorContainer: Color(0XFF1E1E1E),

    // On colors(text colors)
    onBackground: Color(0XFFD2D3D3),
    onInverseSurface: Color(0XFFD2D3D3),
    onPrimary: Color(0XFF1F2223),
    onPrimaryContainer: Color(0XFFD2D3D3),
    onSecondary: Color(0XFFD2D3D3),
    onSecondaryContainer: Color(0XFF1E1E1E),
    onTertiary: Color(0XFFD2D3D3),
    onTertiaryContainer: Color(0XFF1E1E1E),

    // Other colors
    outline: Color(0XFF1F2223),
    outlineVariant: Color(0XFF1E1E1E),
    scrim: Color(0XFF1E1E1E),
    shadow: Color(0XFF1F2223),

    // Inverse colors
    inversePrimary: Color(0XFF1E1E1E),
    inverseSurface: Color(0XFF1F2223),

    // Pending colors
    onSurface: Color(0XFFD2D3D3),
    onSurfaceVariant: Color(0XFF1E1E1E),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // BlueGray
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray900 => Color(0XFF363939);

  // Gray
  Color get gray100 => Color(0XFFF6F6F6);
  Color get gray700 => Color(0XFF57595A);

  // Orange
  Color get orange50 => Color(0XFFFFE5D3);
  Color get orange5001 => Color(0XFFFFF0E5);
  Color get orange900 => Color(0XFFCC5602);
  Color get orangeA700 => Color(0XFFFF6C03);

  // Red
  Color get red800 => Color(0XFFC52727);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
