name: mandar_purushottam_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_database: ^10.4.5
  firebase_auth: ^4.17.4
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Figtree
      fonts: 
        - asset: assets/fonts/FigtreeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/FigtreeRegular.ttf
          weight: 400
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
