import 'package:mandar_purushottam_s_application1/UserModel/RecipeModel.dart';

List<RecipeModel> defaultRecipes = [
  RecipeModel(
    recipeName: "Sabudana Khichdi",
    recipeDescription:
        "Rinse sabudana under cold water until water runs clear. Soak sabudana in water just enough to cover them for 4-6 hours or overnight. After soaking, fluff the sabudana gently with a fork to separate the pearls. Heat ghee or oil in a pan. Add cumin seeds and let them splutter. Add chopped green chilies and diced potatoes. Sauté until potatoes turn golden brown. Add soaked sabudana and crushed peanuts. Mix well. Cook on low heat, stirring occasionally, until sabudana pearls turn translucent and become soft. Season with salt and mix well. Garnish with fresh coriander leaves. Serve hot with lemon wedges on the side, if desired",
    ingredients: [
      IngredientModel(name: "Sabudana", quantity: 340, unit: "g"),
      IngredientModel(name: "Medium Potatoes", quantity: 2, unit: "unit"),
      IngredientModel(name: "Green Chillies", quantity: 2, unit: "unit"),
      IngredientModel(name: "Roasted Peanuts", quantity: 170, unit: "g"),
      IngredientModel(name: "Cumins Seeds", quantity: 5, unit: "g"),
      IngredientModel(name: "Ghee", quantity: 10, unit: "ml"),
      IngredientModel(name: "Salt", quantity: 5, unit: "g"),
    ],
  ),
  RecipeModel(
    recipeName: "Chole Bhature",
    recipeDescription:
        "For Chole, Sauté onions, ginger, garlic, and green chilies. Add tomatoes and spices. Cook until tomatoes are soft. Add chickpeas and cook for 10-15 mins. For Bhature, Mix flour, semolina, yogurt, sugar, baking powder, and salt. Knead into a soft dough. Rest for 2 hours. Roll into circles and fry until golden brown. Serve hot Chole with Bhature, garnished with fresh coriander leaves",
    ingredients: [
      IngredientModel(name: "Chickpeas", quantity: 400, unit: "g"),
      IngredientModel(name: "Medium Onions", quantity: 2, unit: "unit"),
      IngredientModel(name: "Medium Tomatoes", quantity: 2, unit: "unit"),
      IngredientModel(name: "Green Chillies", quantity: 2, unit: "unit"),
      IngredientModel(name: "Ginger", quantity: 1, unit: "unit"),
      IngredientModel(name: "Garlic Cloves", quantity: 5, unit: "unit"),
      IngredientModel(name: "Cumin Seeds", quantity: 5, unit: "g"),
      IngredientModel(name: "Turmeric Powder", quantity: 5, unit: "g"),
      IngredientModel(name: "Coriander Powder", quantity: 10, unit: "g"),
      IngredientModel(name: "Cumin Powder", quantity: 5, unit: "g"),
      IngredientModel(name: "Garam Masala", quantity: 5, unit: "g"),
      IngredientModel(name: "Red Chilli Powder", quantity: 5, unit: "g"),
      IngredientModel(name: "Salt", quantity: 5, unit: "g"),
      IngredientModel(name: "Oil", quantity: 10, unit: "ml"),
      IngredientModel(name: "All-Purpose Flour", quantity: 680, unit: "g"),
      IngredientModel(name: "Semolina", quantity: 170, unit: "g"),
      IngredientModel(name: "Yogurt", quantity: 170, unit: "g"),
      IngredientModel(name: "Sugar", quantity: 5, unit: "g"),
      IngredientModel(name: "Baking Powder", quantity: 5, unit: "g"),
    ],
  ),
  RecipeModel(
    recipeName: "Veg Biryani",
    recipeDescription:
        "Heat ghee or oil in a pressure cooker or heavy-bottomed pan. Add cumin seeds and let them splutter. Add sliced onions and sauté until golden brown. Add minced garlic, grated ginger, and slit green chilies. Sauté for a minute. Add chopped tomatoes and cook until they turn soft and mushy. Add mixed vegetables, biryani masala, turmeric powder, red chili powder, and salt. Mix well. Add soaked and drained rice. Stir gently to mix everything evenly. Add yogurt and enough water (about 2 cups) to cover the rice and vegetables. Stir gently. Close the pressure cooker lid and cook on medium heat for 1 whistle or cook covered on low heat until the rice is cooked and the vegetables are tender (about 15-20 minutes). Once done, let the pressure release naturally. Fluff the biryani gently with a fork. Garnish with fresh coriander leaves and fried onions (if using). Optionally, drizzle saffron-infused milk over the biryani for added flavor and aroma. Serve hot with raita or yogurt on the side.",
    ingredients: [
      IngredientModel(name: "Basmati Rice", quantity: 340, unit: "g"),
      IngredientModel(name: "Carrots", quantity: 170, unit: "g"),
      IngredientModel(name: "Peas", quantity: 170, unit: "g"),
      IngredientModel(name: "Beans", quantity: 170, unit: "g"),
      IngredientModel(name: "Cauliflower", quantity: 170, unit: "g"),
      IngredientModel(name: "Onion", quantity: 1, unit: "unit"),
      IngredientModel(name: "Green Chillies", quantity: 2, unit: "unit"),
      IngredientModel(name: "Garlic Cloves", quantity: 2, unit: "unit"),
      IngredientModel(name: "Ginger", quantity: 1, unit: "unit"),
      IngredientModel(name: "Yogurt", quantity: 170, unit: "g"),
      IngredientModel(name: "Biryani Masala", quantity: 5, unit: "g"),
      IngredientModel(name: "Turmeric Powder", quantity: 3, unit: "g"),
      IngredientModel(name: "Red Chilli Powder", quantity: 5, unit: "g"),
      IngredientModel(name: "Cumin Seeds", quantity: 5, unit: "g"),
      IngredientModel(name: "Ghee", quantity: 14, unit: "ml"),
    ],
  ),
  RecipeModel(
    recipeName: "Veg Pulav",
    recipeDescription:
        "Heat ghee or oil in a pressure cooker or heavy-bottomed pan. Add cumin seeds and let them splutter. Add sliced onions and sauté until golden brown. Add minced garlic, grated ginger, and slit green chilies. Sauté for a minute. Add chopped tomatoes and cook until they turn soft. Add diced carrots, green peas, mixed vegetables, and salt. Sauté for 2-3 minutes. Drain the soaked rice and add it to the vegetables. Stir gently to mix. Pour water or vegetable broth over the rice and vegetables. Stir well. Close the pressure cooker lid and cook on medium heat for 1 whistle or cook covered on low heat until the rice is cooked and the water is absorbed (about 12-15 minutes). Once done, let the pressure release naturally. Fluff the pulav gently with a fork. Garnish with fresh coriander leaves. Serve hot with raita or yogurt on the side.",
    ingredients: [
      IngredientModel(name: "Basmati Rice", quantity: 340, unit: "g"),
      IngredientModel(name: "Onion", quantity: 1, unit: "unit"),
      IngredientModel(name: "Tomato", quantity: 1, unit: "unit"),
      IngredientModel(name: "Carrot", quantity: 1, unit: "unit"),
      IngredientModel(name: "Green Peas", quantity: 1, unit: "unit"),
      IngredientModel(name: "Beans", quantity: 80, unit: "g"),
      IngredientModel(name: "Garlic Cloves", quantity: 2, unit: "unit"),
      IngredientModel(name: "Ginger", quantity: 1, unit: "unit"),
      IngredientModel(name: "Green Chillies", quantity: 2, unit: "unit"),
      IngredientModel(name: "Cumin Seeds", quantity: 5, unit: "g"),
      IngredientModel(name: "Ghee", quantity: 30, unit: "ml"),
      IngredientModel(name: "Vegetable Broth", quantity: 680, unit: "ml"),
      IngredientModel(name: "Coriander Leaves", quantity: 5, unit: "g"),
    ],
  ),
];
